### ISSUE TITLE
Translate module broken.

### ISSUE THREAD

**Issue by clientNaN** [noother/Nimda2#2]
Nimda doesn't translate any language.

Just returns
Translation:

**Comment by clientNaN** [comment]
Looks like Google changed their Translate Website.
An option would be to use the official Google API?

Code example:
http://www.daniweb.com/code/snippet217245.html

**Comment by livinskull** [comment]
added translate API conform libInternet::googleTranslate()
translate works again ;)

**Comment by noother** [comment]
livinskull fixed it, thx :) - closed
